name: suger
description: "A diabetes tracking app"


version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.18.0
  path_provider: ^2.0.13
  permission_handler: ^10.4.2
  fl_chart: ^0.50.1
  pdf: ^3.10.1
  open_file: ^3.0.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/google_logo.png
